# Generated by Django 4.2 on 2023-05-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_level_id_user_level_record_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_level_record',
            name='focus',
        ),
    ]
